source 'https://rubygems.org'
ruby '2.1.1'

gem 'sinatra', require: 'sinatra/base'
gem 'sinatra-activerecord'

gem 'activesupport', '~>' '4.1.11'
gem 'builder'
gem 'closure-compiler'
gem 'coffee-script'
gem 'eco'
gem 'erubis'
gem 'dalli'
gem 'i18n'
gem 'json'
gem 'memcachier'
gem 'rake'
gem 'rack', '~>' '1.5.4'
gem 'rack-ssl'
gem 'markdown'
gem 'redcarpet'
gem 'rack-standards'
gem 'sinatra-contrib', github: 'maccman/sinatra-contrib'
gem 'sprockets', '~>' '2.12.3'
gem 'sprockets-memcache-store'
gem 'stylus'
gem 'stylus-source'
gem 'sqlite3'
gem 'unicorn'
gem 'uglifier'
gem 'yui-compressor'

group :development do
  gem 'thin'
end
